openapi: 3.0.3
info:
  title: API de Pacotes de Viagem
  description: API REST para o gerenciamento de pacotes de viagem.
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Testes

tags:
  - name: Pacotes
    description: Operações relacionadas aos pacotes de viagem

paths:
  /pacotes:
    get:
      tags:
        - Pacotes
      summary: Listar todos os pacotes de viagem
      description: Retorna uma lista com todos os pacotes de viagem disponíveis.
      responses:
        '200':
          description: Operação bem-sucedida.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pacote'
        default:
          description: Erro inesperado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      tags:
        - Pacotes
      summary: Criar um novo pacote de viagem
      description: Adiciona um novo pacote de viagem ao sistema.
      requestBody:
        description: Objeto do pacote que será adicionado.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pacote'
      responses:
        '201':
          description: Pacote criado com sucesso.
        '400':
          description: Requisição inválida, pacote não foi criado.
        default:
          description: Erro inesperado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /pacotes/{pacoteId}:
    parameters:
      - name: pacoteId
        in: path
        required: true
        description: ID do pacote a ser altereado.
        schema:
          type: string
    get:
      tags:
        - Pacotes
      summary: Visualizar um pacote de viagem específico
      description: Retorna os detalhes de um único pacote de viagem pelo seu ID.
      responses:
        '200':
          description: Operação bem-sucedida.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pacote'
        '404':
          description: Pacote não encontrado.
        default:
          description: Erro inesperado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      tags:
        - Pacotes
      summary: Alterar um pacote de viagem
      description: Atualiza os dados de um pacote de viagem existente.
      requestBody:
        description: Objeto do pacote com os dados atualizados.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pacote'
      responses:
        '200':
          description: Pacote atualizado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pacote'
        '400':
          description: Requisição inválida, pacote não foi atualizado.
        '404':
          description: Pacote não encontrado.
        default:
          description: Erro inesperado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      tags:
        - Pacotes
      summary: Remover um pacote de viagem
      description: Remove um pacote de viagem pelo seu ID.
      responses:
        '204':
          description: Pacote removido com sucesso.
        '404':
          description: Pacote não encontrado.
        default:
          description: Erro inesperado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Pacote:
      type: object
      properties:
        descricao:
          type: string
          example: "lorem ipsum dolor"
        localidade:
          $ref: '#/components/schemas/Localidade'
        itens:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/TransladoAereo'
              - $ref: '#/components/schemas/Hospedagem'
              - $ref: '#/components/schemas/LocacaoVeiculo'
      xml:
        name: pacote

    Cliente:
      type: object
      properties:
        nome:
          type: string
          example: "John Doe"
        dataNascimento:
          type: string
          format: date
          example: "26-01-2001"
      xml:
        name: cliente

    Contratacao:
      type: object
      properties:
        valor:
          type: number
          format: double
          example: 140.50
        dataContratacao:
          type: string
          format: date
          example: "26-01-2001"
        cliente:
          $ref: '#/components/schemas/Cliente'
        pacote:
          $ref: '#/components/schemas/Pacote'
      xml:
        name: contratacao


    Hospedagem:
      type: object
      properties:
        itemtype:
          type: string
          example: "hospedagem"
        preco:
          type: number
          format: double
          example: 140.50
        nomeHotel:
          type: string
          example: "John Doe Hotel"
        endereco:
          type: string
          example: "Rua do Gab 123"
      xml:
        name: hospedagem


    LocacaoVeiculo:
      type: object
      properties:
        itemtype:
          type: string
          example: "locacaoVeiculo"
        preco:
          type: number
          format: double
          example: 140.50
        marca:
          type: string
          example: "Subaru"
        modelo:
          type: string
          example: "Imprenza WRTX STI"


    TransladoAereo:
      type: object
      properties:
        itemtype:
          type: string
          example: "transladoAereo"
        preco:
          type: number
          format: double
          example: 140.50
        companiaAerea:
          type: string
          example: "British Airways"
        numeroVoo:
          type: string
          example: "BA246"

    Localidade:
      type: object
      properties:
        descricao:
          type: string
          example: "Rua dos Gabs"

    Error:
      type: object
      properties:
        codigo:
          type: string
        mensagem:
          type: string
